'''
# fake code:
   repeat R times:<br>
       calculate whole<br>
       use alpha*gradient to update w<br>
       return w 
'''

here comes the situation that we have 100 datas ,each data has 2 features(x1,x2)

In [ ]:
import math as exp
import numpy as np 
def loadData():
    dataMat = []  
    labelMat = []
    fr = open('testSet.dat')
    for line in fr.readlines():
        lineArr = line.strip().split()
        dataMat.append([1.0,float(lineArr[0]),float(lineArr[1])])
        labelMat.append(int(lineArr[2]))
    return dataMat,labelMat

def sigmoid(inX):
    return 1.0/(1+exp(-inX))

def gradAscent(dataMatIn, classLabels):
    datdMatrix = np.mat(dataMatIn)
    labelMat = np.mat(classLabels).transpose()
    m,n = np.shape(datdMatrix)
    alpha = 0.1 #normal alpha
    maxCycles = 500
    weights = np.ones((n,1)) #initilize
    for k in range(maxCycles):
        h = sigmoid(datdMatrix*weights)
        error = labelMat - h # every column minus h
        weights = weights + alpha*datdMatrix.transpose()*error #update
    return weights

#draw the picture
def plotBestFit(wei):
    import matplotlib.pyplot as plt
    weights = wei.getA()
    '''
    Return self as an ndarray object. Equivalent to np.asarray(self).
    '''
    dataMat,labelMat = loadData()
    dataArr = np.array(dataMat)
    n =np.shape(dataArr)[0]
    xcord1 = []
    ycord1 = []
    xcord2 = []
    ycord2 = []
    for i in range(n):
        if int(labelMat[i]) == 1:
            xcord1.append(dataArr[i,1]); ycord1.append(dataArr[i,2])
        else:
            xcord2.append(dataArr[i,1]); ycord2.append(dataArr[i,2])
    fig = plt.figure()
    ax = fig.add_subplot(111) #大致意思就是输入 三位数字，abc，根据abc将原图划分成a行，b列。那么就会将原图划分成a*b个子图，然后c就是我们的下标。我们通过c来指定展示我们要的子图。
    ax.scatter(xcord1,ycord1,s=30,c='red',marker='s')
    ax.scatter(xcord2,ycord2,s=30,c='green')
    x = np.arange(-3.0,3.0,0.3)
    y =(-weights[0]-weights[1]*x)/weights[2]
    ax.plot(x,y)
    plt.xlabel('X1');plt.ylabel('X2')
    plt.show()


dataArr,LabelMat = loadData()
gradAscent(dataArr,LabelMat)



    ''' np.ones()

Parameters

shape : int or sequence of ints

    Shape of the new array, e.g., (2, 3) or 2.

dtype : data-type, optional

    The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

order : {'C', 'F'}, optional, default: C

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

Returns

out : ndarray

    Array of ones with the given shape, dtype, and order.

Examples

>>> np.ones(5)

array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))

array([[1.],
       [1.]])

>>> s = (2,2)

>>> np.ones(s)

array([[1.,  1.],
       [1.,  1.]])

    ''' 

## random grad_descent

notice how the use of sigmond change and the change of w

In [ ]:
def stocGradAscent1(dataMatrix, classLabels, numIter=150):
    m,n = np.shape(dataMatrix)
    weights = np.ones(n)   #initialize to all ones
    for j in range(numIter):
        dataIndex = range(m)
        for i in range(m):
            alpha = 4/(1.0+j+i)+0.0001    #apha decreases with iteration, does not 
            randIndex = int(np.random.uniform(0,len(dataIndex)))#go to 0 because of the constant
            h = sigmoid(sum(dataMatrix[randIndex]*weights))
            error = classLabels[randIndex] - h
            weights = weights + alpha * error * dataMatrix[randIndex]
            del(dataIndex[randIndex])
    return weights

# true example

now we got true example concerning classify. we choose to classify by logistic ,p over 0.5 return 1.0,below 0.5 return 0.0

In [4]:
def classifyVector(inX, weights):
    prob = sigmoid(sum(inX*weights))
    if prob > 0.5: return 1.0
    else: return 0.0

def colicTest():
    frTrain = open('horseColicTraining.txt'); frTest = open('horseColicTest.txt')
    trainingSet = []; trainingLabels = []
    for line in frTrain.readlines():
        currLine = line.strip().split('\t')
        lineArr =[]
        for i in range(21):
            lineArr.append(float(currLine[i]))
        trainingSet.append(lineArr)
        trainingLabels.append(float(currLine[21]))
    trainWeights = stocGradAscent1(np.array(trainingSet), trainingLabels, 1000)
    errorCount = 0; numTestVec = 0.0
    for line in frTest.readlines():
        numTestVec += 1.0
        currLine = line.strip().split('\t')
        lineArr =[]
        for i in range(21):
            lineArr.append(float(currLine[i]))
        if int(classifyVector(np.array(lineArr), trainWeights))!= int(currLine[21]):
            errorCount += 1
    errorRate = (float(errorCount)/numTestVec)
    print ("the error rate of this test is: %f" % errorRate)
    return errorRate

def multiTest():
    numTests = 10; errorSum=0.0
    for k in range(numTests):
        errorSum += colicTest()
    print ("after %d iterations the average error rate is: %f" % (numTests, errorSum/float(numTests)))

# Logistic Regression in skicit-learn
doc location:https://scikit-learn.org.cn/view/378.html

sklearn.linear_model.LogisticRegression


